server:
  port: 8080

eureka:
  instance:
    hostname: ${HOSTNAME:rally}
  client:
    serviceUrl:
      defaultZone: http://registry:8761/eureka/

rp:
  mongo:
    host: mongodb
    port: 27017
    dbName: reportportal
    user:
    password:

spring:
  redis:
    host: redis
    port: 6379
  cloud:
    consul:
      host: registry
      discovery:
        hostname: ${HOSTNAME:rally}
        prefer-ip-address: false
